Modify rust-tapyrus branch for using malfix_txid
chaintope/rust-electrum-client pull request #2
Opened 2024-07-08 08:09 UTC by rantan

2024-07-16 05:06 UTC, Yamaguchi requested changes

2024-07-16 05:06 UTC, Yamaguchi commented on .github/workflows/cont_integration.yml
> +      - name: Pin dependencies for MSRV
ccのバージョンが古くてビルドが通らない件に関して、tdkではrustのバージョンを1.67.0にして対処してます。
https://github.com/chaintope/tdk/commit/844dd2b9f220a16b2e0e59bd79aedcba6290cebb

こちらも同様にサポートするバージョンを1.67にあげても良いと思いました。

2024-07-17 02:21 UTC, rantan commented on .github/workflows/cont_integration.yml
> +      - name: Pin dependencies for MSRV
了解です。そのように対応します。

2024-07-18 05:55 UTC, Yamaguchi approved these changes

2024-07-18 06:53 UTC, merged